path: /Users/amorri63/Library/Mobile Documents/com~apple~CloudDocs/Photos/Originals/Scans/_To_Do
  # /Users/amorri63/Library/Mobile Documents/com~apple~CloudDocs/Photos/Originals/Photos/_To-Do
  # /Users/amorri63/Library/Mobile Documents/com~apple~CloudDocs/Photos/Originals/Scans/KFM and DRM/KFM 1958-64 Edmonton
  # C:/Users/craig/iCloudDrive/Photos/Originals/Scans/KFM and DRM/KFM 1959 Kay and Ross Wedding
image_prefix: KFM
